# table
users:
    hash_key:
        name: userId
        type: string
    indexes:
        - name: email
          type: string
        - name: createTimestamp
          type: number
        - name: settings
          type: binary